import {
	BACKEND_ADD_IMAGE_PATH,
	BACKEND_ADMINS_PATH,
	BACKEND_AUTH_PATH,
	BACKEND_CATEGORIES_PATH,
	BACKEND_HOST,
	BACKEND_MEDIA_PATH,
	BACKEND_NEWS_PATH,
	BACKEND_NEWS_READ_PATH,
	BACKEND_PORT,
	BACKEND_PROTOCOL,
	BACKEND_REFRESH_TOKEN_PATH,
	NEWS_CHECK_INTERVAL_SECONDS,
	SOCIAL_FACEBOOK,
	SOCIAL_INSTAGRAM,
	SOCIAL_SMUGMUG,
	SOCIAL_TWITTER,
	SOCIAL_YOUTUBE,
	USER_KEY,
} from 'react-native-dotenv';


const cfg = {
	BACKEND_PROTOCOL,
	BACKEND_PORT, BACKEND_HOST,
	BACKEND_ADMINS_PATH,
	BACKEND_CATEGORIES_PATH,
	///// NEWS
	BACKEND_NEWS_PATH,
	BACKEND_NEWS_READ_PATH,
	BACKEND_ADD_IMAGE_PATH,
	BACKEND_MEDIA_PATH,
	///// AUTH
	BACKEND_AUTH_PATH,
	BACKEND_REFRESH_TOKEN_PATH,
	NEWS_CHECK_INTERVAL_SECONDS,
	USER_KEY,
	//social media links
	SOCIAL_FACEBOOK,
	SOCIAL_YOUTUBE,
	SOCIAL_INSTAGRAM,
	SOCIAL_SMUGMUG,
	SOCIAL_TWITTER,
};

//console.log(`config:${cfg.NEWS_CHECK_INTERVAL_SECONDS}`);
console.info(`config:${JSON.stringify(cfg, null, 2)}`);

export default cfg;
